Check sheldon/plugins.lock exist.

diff --git a/.github/workflows/arch_manjaro.yml b/.github/workflows/arch_manjaro.yml
--- a/.github/workflows/arch_manjaro.yml
+++ b/.github/workflows/arch_manjaro.yml
@@ -12,22 +12,31 @@ jobs:
       image: archlinux:latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Update pacman
         run: pacman -Syu -q --noconfirm
+
       - name: Install sudo
         run: pacman -Sy -q --noconfirm sudo git curl
+
       - name: Run chezmoi
         run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply radiol
+
       # # Error Check
-      - name: Load zsh
+      - name: Exec zsh and check sheldon/plugins.lock exist.
         run: |
           zsh -i -l -c exit
-          zsh -i -l -c exit 2> error.log; cat error.log
-          cat error.log
-          if [ -s error.log ]; then false; fi
+          if [ -f "$HOME/.local/share/sheldon/plugins.lock" ]; then
+            echo "Sheldon plugins loaded successfully."
+          else
+            echo "Failed to load Sheldon plugins."
+            exit 1
+          fi
+
       - name: Check lazy.nvim dir
         run: |
           ls ~/.local/share/nvim/lazy/
+
       - name: Check IME config file(arch only)
         run: cat ~/.config/environment.d/im.conf
 
@@ -39,22 +48,31 @@ jobs:
       image: manjarolinux/base:latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Update pacman
         run: pacman -Syu -q --noconfirm
+
       - name: Install sudo
         run: pacman -Sy -q --noconfirm sudo git curl
+
       - name: Run chezmoi
         run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply radiol
+
       # # Error Check
-      - name: Load zsh
+      - name: Exec zsh and check sheldon/plugins.lock exist.
         run: |
           zsh -i -l -c exit
-          zsh -i -l -c exit 2> error.log; cat error.log
-          cat error.log
-          if [ -s error.log ]; then false; fi
+          if [ -f "$HOME/.local/share/sheldon/plugins.lock" ]; then
+            echo "Sheldon plugins loaded successfully."
+          else
+            echo "Failed to load Sheldon plugins."
+            exit 1
+          fi
+
       - name: Check lazy.nvim dir
         run: |
           ls ~/.local/share/nvim/lazy/
+          
       - name: Check IME config file does NOT exist(arch only)
         run: |
           if test -f "~/.config/environment/im.conf"; then
diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -19,12 +19,15 @@ jobs:
         run: /bin/bash -c "$(curl -fsLS chezmoi.io/get)" -- init --apply radiol
 
       # Error Check
-      - name: Exec zsh
+      - name: Exec zsh and check sheldon/plugins.lock exist.
         run: |
           zsh -i -l -c exit
-          zsh -i -l -c exit 2> error.log; cat error.log
-          cat error.log
-          if [ -s error.log ]; then false; fi
+          if [ -f "$HOME/.local/share/sheldon/plugins.lock" ]; then
+            echo "Sheldon plugins loaded successfully."
+          else
+            echo "Failed to load Sheldon plugins."
+            exit 1
+          fi
 
       - name: Check lazy.nvim dir
         run: ls ~/.local/share/nvim/lazy/
