Check ignored file does Not exist.

diff --git a/.github/workflows/arch_manjaro.yml b/.github/workflows/arch_manjaro.yml
--- a/.github/workflows/arch_manjaro.yml
+++ b/.github/workflows/arch_manjaro.yml
@@ -29,7 +29,9 @@ jobs:
         run: |
           ls ~/.local/share/nvim/lazy/
       - name: Check IME config file(arch only)
-        run: ls ~/.config/environment.d/
+        run: cat ~/.config/environment.d/im.conf
+
+
   manjaro-test:
     runs-on: ubuntu-latest
     # if: ${{ contains(github.event.head_commit.message, "[CI]") }}
@@ -54,4 +56,8 @@ jobs:
         run: |
           ls ~/.local/share/nvim/lazy/
       - name: Check IME config file does NOT exist(arch only)
-        run: ls ~/.config/
+        run: |
+          if test -f "~/.config/environment/im.conf"; then
+            echo "Error: Ignored file exists"
+            exit 1
+          fi
diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -32,3 +32,9 @@ jobs:
       - name: Check lazy.nvim dir
         run: ls ~/.local/share/nvim/lazy/
 
+      - name: Check IME config file does NOT exist(arch only)
+        run: |
+          if test -f "~/.config/environment/im.conf"; then
+            echo "Error: Ignored file exists"
+            exit 1
+          fi
